name: pin_kodum
description: Pin Kodum — Numeroloji temelli kişisel farkındalık uygulaması.
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0

  # Navigation
  go_router: ^13.2.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Local Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.0

  # Localization
  flutter_localizations:
    sdk: flutter

  # IAP
  in_app_purchase: ^3.2.0

  # PDF
  pdf: ^3.10.8
  printing: ^5.13.1
  share_plus: ^12.0.2
  path_provider: ^2.1.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # Utils
  intl: ^0.20.2
  uuid: ^4.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
